### ISSUE TITLE
Some insecure configurations listed in rule

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/Crypto-API-Rules#13]
According to the crypto team of Oracle, we are missing some specifications/specified them insecurely:

- [x] Key size rules include insecure sizes (eg KeyPairGenerator - 1024 bit keys, DESede   112)
- [x] There  are a number of secure algorithms for which there are no rules. Eg. ECC  algorithms, CCM Cipher mode, AES KW (key wrap)
- [x] For  PBEKeySpec, the iteration count rule for PBE is too small (>= 1000)

**Comment by kruegers** [comment]
2) Thanks for the pointer. Do you have any more info about them? Also, is this list complete?
3) What should the iteration count be?

**Comment by johspaeth** [comment]
2. No, we did not get more information, I assume this needs further discussion with crypto experts.
3. I can't tell. [NIST](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf) recommended in 2010 a mimimum value of 1000, I assume you got the value from there? It also states 

>  shall be selected as large as possible, as long as the time required to generate the key using the 
entered password is acceptable for the users

I wonder what improvement we could deliver here.

**Comment by kmindi** [comment]
https://pages.nist.gov/800-63-3/sp800-63b.html#sec5 states
> the iteration count SHOULD be as large as verification server performance will allow, typically at least 10,000 iterations.

**Comment by kruegers** [comment]
Thanks, @kmindi. I have adopted the suggestion. That said, above, I was rather asking for what value Oracle would like to see there. 
@johspaeth I view this aspect as solved for now as it follows the NIST suggestion. If Oracle prefers a different value, feel free to uncheck the box above.

Concerning 2), I will research the three mentioned algorithms and update the rules accordingly. If there is other stuff that is missing, Oracle should give us a more complete list.
