### ISSUE TITLE
Check BigInteger arguments to constructor of DSAParameterSpec, DHParameterSpec

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/Crypto-API-Rules#14]
[DHParameterSpec](https://docs.oracle.com/javase/7/docs/api/javax/crypto/spec/DHParameterSpec.html) and [DSAParameterSpec](https://docs.oracle.com/javase/7/docs/api/java/security/spec/DSAParameterSpec.html) takes BigInteger as arguments. The rules can additionally check on the size of these integers.

**Comment by kruegers** [comment]
I'm not entirely sure what to specify here. Can you please elaborate?

**Comment by johspaeth** [comment]
We can add Constraints to restrict the Integers, even though they are wrappers (BigIntegers)
