### ISSUE TITLE
Rule for cipher should allow multiple `init` calls

### ISSUE THREAD

**Issue by kmindi** [CROSSINGTUD/Crypto-API-Rules#17]
I saw an error that cipher expected an update/doFinal call where I was calling init (AGAIN!).

Is it not correct to reuse a created instance of a cipher object?

The JDK states
> Note that when a Cipher object is initialized, it loses all previously-acquired state. In other words, initializing a Cipher is equivalent to creating a new instance of that Cipher and initializing it.

So this should allow me to call `init` again. If that is true, the rule should be updated.

**Comment by kruegers** [comment]
Hey @kmindi,
We had previously been told that there are certain cases, in which a re-initialization does not remove any possibly existing state information. We could not confirm this now, however. I have hence updated the rule accordingly. Thanks for reporting this issue.
