### ISSUE TITLE
Model BouncyCastle (Lightweight API)

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/Crypto-API-Rules#22]

**Comment by rakshitkr** [comment]
The following rules have been created
1. Cipher engines conforming to `BlockCipher` interface
- [x] `AESEngine`
- [x] `AESLightEngine`
- [x] `DESEngine`

2. Cipher engines conforming to `AsymmetricBlockCipher` interface
- [x] `RSAEngine`

3. Modes on top of a simple cipher
- [x] `CBCBlockCipher` *extends* `StreamBlockCipher`
- [x] `CFBBlockCipher` *implements* `BlockCipher`
- [x] `OFBBlockCipher` *extends* `StreamBlockCipher `
- [x] `SICBlockCipher` *extends* `StreamBlockCipher`

3. Various kinds of parameter classes 
- [x] `KeyParameters` *implements* `CipherParameters`
- [x] `AsymmetricKeyParameter` *extends* `CipherParameters `
- [x] `ParametersWithIV` *implements* `CipherParameters `
- [x] `RSAKeyParameter` *extends* `AsymmetricKeyParameter`
- [x] `RSAPrivateCrtKeyParameters` *extends* `RSAKeyParameter`

4. Message Digest conforming to `Digest` interface
- [x] `SHA256Digest`

**Comment by kruegers** [comment]
Great, thanks, @rakshitkr.
Are there classes left to model?

**Comment by rakshitkr** [comment]
@kruegers I finished adding all relevant ones

**Comment by johspaeth** [comment]
Thanks @rakshitkr that ticket now provides us with good details. Focus on the classes and names of Algorithms you find in the current CrySL specs and try to cover at least one class of each of the 12. use cases.

A side question:
Do you have an idea of how much repetition potential rules, for instance, for the Engine classes have? 
Do you think one could generate them (@rbonifacio)?

**Comment by rakshitkr** [comment]
@rbonifacio After having compared all the other engine classes with AESEngine. Below is the list to be autogenerated based on AESEngine
- BlowfishEngine
- CamelliaEngine
- CamelliaLightEngine
- CAST5Engine
- CAST6Engine
- DESedeEngine
- DSTU7624Engine
- GOST28147Engine
- GOST3412_2015Engine
- IDEAEngine
- NoekeonEngine
- NullEngine
- RC2Engine
- RC4Engine
- RC532Engine
- RC564Engine
- RC6Engine
- RijnadaelEngine
- SEEDEngine
- SerpentEngine
- Shacal2Engine
- SkipjackEngine
- SM4Engine
- TEAEngine
- TnepresEngine
- TwofishEngine
- XTEAEngine
