### ISSUE TITLE
All Predicates in REQUIRES block needs to be generated

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/Crypto-API-Rules#29]
According to the [CrySL spec for `BufferedBlockCipher`](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/bouncy_castle/src/de/darmstadt/tu/crossing/bc/BufferedBlockCipher.cryptsl), the `EVENT` block has two constructors 

```Java
c1 : BufferedBlockCipher(mode);     // According to AESTest
c2 : BufferedBlockCipher(engine);   // BlockCipherVectorTest or BlockCipherMonteCarloTest has such usages
Cons := c1 | c2;
```

Hence the `REQUIRES` block has two predicates namely
```Java
generatedMode[mode];   // corresponding to BufferedBlockCipher(mode)
generatedEngine[engine];   // corresponding to BufferedBlockCipher(engine)
```

CryptoAnalysis throws `RequiredPredicateError` error markers for every predicate which is not generated. So even though I use only `BufferedBlockCipher(mode)` in my code and generate the mode properly, I get an error marker for the other constructor

Below is the code snippet of my test case
```Java
...
BlockCipher engine = new AESEngine();
BlockCipher mode = new CBCBlockCipher(engine);
BufferedBlockCipher cipher = new BufferedBlockCipher(mode);
...
```

What Cognicrypt outputs
```Java
RequiredPredicateError violating CrySL rule for BufferedBlockCipher
			First parameter was not properly generated as generated Engine
			at statement: specialinvoke $r10.<org.bouncycastle.crypto.BufferedBlockCipher: void <init>(org.bouncycastle.crypto.BlockCipher)>(r2)
```

**Comment by johspaeth** [comment]
Have you tried debugging the analysis yet? Which predicates are generated at which statements?

To find this out, start debugging from [here](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/10e86fdb0998f84615acba86cdb32a0b2e470758/CryptoAnalysis/src/main/java/crypto/predicates/PredicateHandler.java#L59) and print the statement, variables, and predicates. I would expect a predicate "generatedMode" for mode. If it is not generated, see where the method is called and why it is not generated properly.

**Comment by rakshitkr** [comment]
The predicate "generatedMode" for mode is getting generated properly since `CBCBlockCipher` crySL ENSURES this predicate. But my concern is why is analysis throwing error marker for `generatedEngine[engine]` even though I haven't used `c2 : BufferedBlockCipher(engine)` in my test case.

**Comment by johspaeth** [comment]
Ok, I see.

The static analysis cannot distinguish between the calls to BufferedBlockCipher(engine) and BufferedBlockCipher(mode). Because both constructors use the same type [BlockCipher](https://people.eecs.berkeley.edu/~jonah/bc/org/bouncycastle/crypto/BufferedBlockCipher.html).

Let's discuss that in the meeting.

**Comment by johspaeth** [comment]
Am I correct, that the following code:

```
BlockCipher engine = new AESEngine();
BufferedBlockCipher cipher = new BufferedBlockCipher(engine);
```

is also a valid usage? Can't we just use a single predicate that `AESEngine` generates which is required by `CBCBlockCipher` and that `CBCBlockCipher` simply propagates again?

Concrete:

```
c1 : BufferedBlockCipher(mode);

REQUIRES
generatedEngineOrMode[engineOrMode]
```

and then for `AESEngine` 

```
ENSURES 
generatedEngineOrMode
```

for `CBCBlockCipher`:

```
c1 : CBCBlockCipher(engine);

REQUIRES
generatedEngineOrMode[engine]

ENSURES
generatedEngineOrMode[this]
```

**Comment by rakshitkr** [comment]
Your solution worked. I was able to get rid of all `RequiredPredicateError` error markers. Thanks @johspaeth

**Comment by rakshitkr** [comment]
There is one problem with this solution. Now one can pass `CBCBlockCipher` object instead of `AESEngine` object inside `CFBBlockCipher` constructor. This is because `CBCBlockCipher` crySL ensures `generatedEngineOrMode` and `CFBBlockCipher`crySL requires the same.

The below usage is wrong. But analysis doesn't give any error markers which leads to *False Negative*
```Java
BlockCipher cfb = new CFBBlockCipher(new CBCBlockCipher(new AESEngine()), 16);
```

**Comment by johspaeth** [comment]
Well spotted. Totally makes sense. I don't yet see a solution other than extending the languages by an OR clause for  PREDICATES.

Out of curiousity, does the code above execute?

**Comment by johspaeth** [comment]
Oh well, what if you let AESEngine generate two predicates, and REQUIRE the second one in CBCBlockCipher?

**Comment by rakshitkr** [comment]
> Well spotted. Totally makes sense. I don't yet see a solution other than extending the languages by an OR clause for PREDICATES.
> 
> Out of curiousity, does the code above execute?

Yes... Because both mode and engine are of type `BlockCipher`

**Comment by johspaeth** [comment]
Wow, i would have expected at least an exception.

**Comment by rakshitkr** [comment]
> Oh well, what if you let AESEngine generate two predicates, and REQUIRE the second one in CBCBlockCipher?

This solution worked like a charm. I'm now getting `RequiredPredicateError` error markers for mode inside a mode which is a *True Positive*
