### ISSUE TITLE
Possible CrySL rules to implement from CryptoGuard Crypto-API Benchmark

### ISSUE THREAD

**Issue by enriozuni** [CROSSINGTUD/Crypto-API-Rules#40]
CryptoGuard Crypto-API Benchmark reports misuses that are not found from static analysis tools such as CogniCrypt. In their list of tests, the following CrySL rules are not implemented and therefore headless tests could not be done.

Reference of the issue is in this [link](https://github.com/CROSSINGTUD/CryptoAnalysis/issues/134)

Java classes that are used in the CryptoGuard tests and are not yet implemented as CrySL rules can be found below.
# Checklist:

- [ ] `javax.net.ssl.X509TrustManager`
- [ ] `javax.net.ssl.HostnameVerifier`
- [ ] `javax.net.ssl.SSLSession`
- [ ] `javax.net.ssl.HttpsURLConnection`
- [ ] `javax.net.ssl.SSLSocket`
- [ ] `javax.net.ssl.SSLSockerFactory`
- [ ] `java.security.cert.CertificateException`
- [ ] `java.security.cert.X509Certificate`
- [ ] `java.net.URL`
- [ ] `java.net.MalformedURLException`

**Comment by kruegers** [comment]
I suspect these will become relevant when you work on [this issue](https://github.com/eclipse-cognicrypt/CogniCrypt/issues/334).

**Comment by AndreSonntag** [comment]
javax.net.ssl.X509TrustManager: no security risk
 javax.net.ssl.SSLSession: no security risk
 java.net.URL: no security risk
 javax.net.ssl.HttpsURLConnection: no security risk
 java.security.cert.X509Certificate: no security risk
 
 javax.net.ssl.HostnameVerifier: Interface -> just one method, no implementing classes

 javax.net.ssl.SSLSocket: rule already exsists 
 javax.net.ssl.SSLSockerFactory: rule already exsists
 
 Exceptions are not considered
