### ISSUE TITLE
Enable CrySL rules to disallow certain algorithms

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/Crypto-API-Rules#54]
**Task desc**: current ruleset only allows certain algorithms but doesn't disallow any. 
**TODO**: automatic generation of crysl rules to disallow certain algorithms (Eg. AES/ECB doesn't work)

**Comment by rakshitkr** [comment]
The following ruleset of CBCBlockCipher only takes AES as the required engine while disallowing all the other engines such as DES, BlowFish etc.

```
SPEC org.bouncycastle.crypto.modes.CBCBlockCipher

OBJECTS
	org.bouncycastle.crypto.BlockCipher engine;
	
EVENTS
	c : CBCBlockCipher(engine);
	
ORDER
	c

REQUIRES
	generatedAESEngine[engine];
	
ENSURES
	generatedCBCBlockCipher[this];
```

The following test cases verify the above scenario
```
	@Test
	public void testOne() {
		BlockCipher engine = new BlowfishEngine();
		Assertions.hasEnsuredPredicate(engine);
		BlockCipher mode = new CBCBlockCipher(engine);   // not allowed
		Assertions.notHasEnsuredPredicate(mode);
		PaddedBufferedBlockCipher cipher = new PaddedBufferedBlockCipher(mode);
	}
	
	@Test
	public void testTwo() {
		BlockCipher engine = new DESEngine();
		Assertions.hasEnsuredPredicate(engine);
		BlockCipher mode = new CBCBlockCipher(engine);   // not allowed
		Assertions.notHasEnsuredPredicate(mode);
		PaddedBufferedBlockCipher cipher = new PaddedBufferedBlockCipher(mode);
	}
	
	@Test
	public void testThree() {
		BlockCipher engine = new AESEngine();
		Assertions.hasEnsuredPredicate(engine);
		BlockCipher mode = new CBCBlockCipher(engine);   // allowed
		Assertions.hasEnsuredPredicate(mode);
		PaddedBufferedBlockCipher cipher = new PaddedBufferedBlockCipher(mode);
	}
```

**Comment by kruegers** [comment]
Tests one and two should already cause warnings because, in neither case, engine receives a AESEngine predicate. So, Assertions.hasEnsuredPredicate(engine) should fail in both cases. Is that not what happens?

**Comment by rakshitkr** [comment]
@johspaeth could you please describe scenarios where it will be actually necessary to make the above requirement more explicit?

**Comment by rakshitkr** [comment]
@kruegers `testOne` & `testTwo` has `Assertions.notHasEnsuredPredicate` after mode instantiation. Hence they both pass.

**Comment by kruegers** [comment]
Are there rules for DESEngine and BlowfishEngine?

**Comment by rakshitkr** [comment]
> Are there rules for DESEngine and BlowfishEngine?

Not yet!

**Comment by kruegers** [comment]
Then, the test case as they are there should fail. Line 2 in all three cases says:
Assertions.hasEnsuredPredicate(engine);
If there are no rules for DESEngine and BlowfishEngine, the two engine objects can never receive a predicate. Does that work?

**Comment by rakshitkr** [comment]
> Then, the test case as they are there should fail. Line 2 in all three cases says:
> Assertions.hasEnsuredPredicate(engine);
> If there are no rules for DESEngine and BlowfishEngine, the two engine objects can never receive a predicate. Does that work?

You are right! But the test cases seems to pass.

**Comment by rakshitkr** [comment]
This requirement only makes sense when the `REQUIRES` predicate is *generatedEngine* instead of *generatedAESEngine*. In that case, any object having the predicate *generatedEngine* will satisfy the `REQUIRES` block of *CBCBlockCipher* regardless of whether it is *AESEngine*, *RSAEngine*, etc.. However, since the CBCBlockCipher `REQUIRES` *generatedAESEngine* only all the other engine types are disallowed by default since the CrySL specification follows **whitelisting approach.**

**Comment by rakshitkr** [comment]
@kruegers The test cases *testOne()* and *testTwo()* fails as you described above since the expected predicate `generatedAESEngine` is missing. Whereas *testThree()* passes since `engine` is of type *AESEngine* and hence gets the predicate `generatedAESEngine`

**Comment by kruegers** [comment]
Ok, if everything works as expected, I'm closing this issue for now.
